name: build mtcode 
on: 
  push:
  workflow_dispatch:

jobs:
  mtcode:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./mtcode
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mtcode:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mtcode:0.1.3
            ghcr.io/${{ github.repository_owner }}/mtcode:latest
            ghcr.io/${{ github.repository_owner }}/mtcode:0.1.3
